name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: copy files to server
    runs-on: ubuntu-22.04
    steps:
    - name: checkout 'main'
      uses: actions/checkout@main
      with:
        ref: main
    - name: copy the files
      uses: appleboy/scp-action@master
      with:
        host:  ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/var/www/radleylewis.com"

